# version: '3.9'

services:

  web_app:
    depends_on:
      - dbserver
    image: rodmosh/door-access-mgm:production
    privileged: true
    devices:
      - "/dev/gpiomem"
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - .prod.env
    volumes:
      - static_volume:/app_root/static
      - log_data:/var/log/app
      - ./provision:/app_root/provision:ro
    networks:
      - door_net

  webserver:
    depends_on:
      - web_app
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/var/www/static
    networks:
      - door_net

  dbserver:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=db_proj
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - door_net

volumes:
  static_volume: {}
  caddy_data: {}
  caddy_config: {}
  postgres_data: {}
  log_data: {}


networks:
  door_net: