services:

  dbserver:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_proj
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_dev_data: {}
