# version: '3.9'

services:

  web-door-access:
    image: rodmosh/door-access-mgm
    command: gunicorn --pythonpath ./proj proj.wsgi --bind 0.0.0.0:8000
    privileged: true
    devices:
      - "/dev/gpiomem"
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/app_root/static
    networks:
      - door_net

  caddy:
    depends_on:
      - web-door-access
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/var/www/static
    networks:
      - door_net

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_DB=example_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  static_volume: {}
  caddy_data: {}
  caddy_config: {}

networks:
  door_net: